config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'welcome#index'

  get 'about' => 'welcome#about'

  get 'brandon' => 'welcome#brandon'

  get 'code' => 'welcome#code'

  get 'welcome/index'

  get 'welcome/about' => 'about'

  resources :users, only: [:show]

  resources :registered_applications

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create, :new]
  end

end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :registered_application

end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events, dependent: :destroy

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :registered_applications
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController

  skip_before_action :verify_authenticity_token

  before_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def create

    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
    @event = Event.new(event_params)
    @event.registered_application = registered_application
      if registered_application.nil?
        render json: "Unregistered application", status: :unprocessable_entity
      elsif @event.save
        render json: @event, status: :created
      else
        render json: {errors: @event.errors}, status: :unprocessable_entity
      end
  end

  def preflight
    head 200
  end

  private

  def event_params
    params.require(:event).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def default_url_options
    {:host => "localhost", :port => "3000"}
  end

  protect_from_forgery with: :exception

end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController

  def index
    @applications = RegisteredApplication.all
  end

  def show
    @application = RegisteredApplication.find(params[:id])

    @events = @application.events.group_by(&:name)
  end

  def new
    @application = RegisteredApplication.new
  end

  def create
    @application = RegisteredApplication.new(app_params)
    @application.user = current_user

    if @application.save
      flash[:success] = "You application has been registered."
      redirect_to @application
    else
      flash[:error] = "There was an error saving your application. Please try again."
      render :new
    end
  end


  def edit
    @application = RegisteredApplication.find(params[:id])
  end

  def update
    @application = RegisteredApplication.find(params[:id])

    @application.assign_attributes(app_params)

    if @application.save
      flash[:notice] = "You application has been updated."
      redirect_to @application
    else
      flash[:error] = "There was an error updating your application. Please try again."
      render :edit
    end

  end

  def destroy
    @application = RegisteredApplication.find(params[:id])

    if @application.destroy
      flash[:notice] = "Application was successfully deleted."
      redirect_to registered_applications_path
    else
      flash[:error] = "There was an error deleting your application."
      redirect_to :back
    end
  end

  private

  def app_params
    params.require(:registered_application).permit(:name, :url)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    if current_user.present?
      @user = params[:id] ? User.find(params[:id]) : current_user

      @user_applications = @user.registered_applications
      
    else
      redirect_to new_user_registration_path
    end
  end

  def index
    User.all
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

    <header id="header">
        <div class="top-bar">
            <div class="container">
                <div class="row">
                  <div class="col-sm-6 col-xs-4">
                  </div>
                    <div class="col-sm-6 col-xs-8">
                       <div class="social">
                            <ul class="social-share">
                                <li><a href="https://twitter.com/b_wieber"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="https://www.linkedin.com/in/brandon-wieber-3574b454"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="https://github.com/BWieber"><i class="fa fa-github"></i></a></li>
                                <li><a href="mailto:brandon.m.wieber@gmail.com"><i class="fa fa-google-plus"></i></a></li>
                            </ul>

                            <div class="search">
                                <form role="form">
                                    <input type="text" class="search-form" autocomplete="off" placeholder="Search">
                                    <i class="fa fa-search"></i>
                                </form>
                           </div>
                       </div>
                    </div>
                </div>
            </div><!--/.container-->
        </div><!--/.top-bar-->

        <nav class="navbar navbar-inverse" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/welcome/index"> BLOCMETRICS </a>
                </div>

                <div class="collapse navbar-collapse navbar-right">
                    <ul class="nav navbar-nav">
                        <li><a href="/code">How It Works</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">About <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li><a href="/brandon">Brandon, The Author</a></li>
                            </ul>
                        </li>

                        <li><%= link_to "Tracked Apps", registered_applications_path %></li>

                        <% if user_signed_in? %>
                        <li> <%= link_to "My Profile", user_path(current_user) %></li>
                        <li> <%= link_to 'Edit profile', edit_user_registration_path  %> </li>
                        <li> <%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>

                        <% else %>
                        <li> <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> </li>
                        <li> <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %> </li>
                        <% end %>



                      </ul>
                      </div>

                    </ul>
                </div>
            </div><!--/.container-->
        </nav><!--/nav-->

    </header><!--/header-->

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>

  <footer id="footer" class="midnight-blue">
      <div class="container">
          <div class="row">
              <div class="col-sm-6">
                  &copy; 2016 Brandon Wieber</a>. All Rights Reserved.
              </div>
              <div class="col-sm-6">
                  <ul class="pull-right">
                      <li><a href="/welcome/index">Home</a></li>
                      <li><a href="/code">About Blocmetrics</a></li>
                      <li><a href="mailto:brandon.m.wieber@gmail.com"><i class="fa fa-google-plus"></i> Contact Brandon</a></li>
                  </ul>
              </div>
          </div>
      </div>
  </footer><!--/#footer-->

</body>
</html>

app/views/registered_applications/create.html.erb
<h1>RegisteredApplications#create</h1>
<p>Find me in app/views/registered_applications/create.html.erb</p>

app/views/registered_applications/destroy.html.erb
<h1>RegisteredApplications#destroy</h1>
<p>Find me in app/views/registered_applications/destroy.html.erb</p>

app/views/registered_applications/edit.html.erb
<h1>RegisteredApplications#edit</h1>
<p>Find me in app/views/registered_applications/edit.html.erb</p>

app/views/registered_applications/index.html.erb
<h1> Currently Tracked Apps </h1>

<% @applications.each do |app| %>
  <div class='media'>
    <h3> <%=link_to app.name, registered_application_path(app) %> </h3>
    <p> <%= app.url %> </p>
  </div>
  <% end %>

app/views/registered_applications/new.html.erb
<h1> Add an Application </h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for @application do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter application name" %>
      </div>

      <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, class: "form-control", placeholder: "Enter application url" %>
      </div>

      <div class="form-group">

        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/registered_applications/show.html.erb
<h1> <%= @application.name %> </h1>

  <h3> Events: </h3>
    <% @events.each do |event, visit| %>
      <h5> Event: <%= event %> </h5>
      <h5> Times Visited: <%= visit.count %> </h5>
        <br>
    <% end %>


    <%= pie_chart @application.events.group(:name).count %>

    <br>

    <%= line_chart @application.events.group_by_day(:created_at).count %>

app/views/registered_applications/update.html.erb
<h1>RegisteredApplications#update</h1>
<p>Find me in app/views/registered_applications/update.html.erb</p>

app/views/users/show.html.erb
<h1> <%= @user.username %>'s Profile
  <% if @user == current_user %>
  <%= link_to "Add Application", new_registered_application_path, class: 'btn btn-success' %>
  <% end %>
</h1>

  <div class='container'>
    <div class='media'>
      <div class='media-body'>
  <% @user_applications.each do |app| %>
  <h3> <%= app.name %> <%= link_to "Delete Application", registered_application_path(app), method: :delete, class: 'btn btn-danger' %> </h3>
  <h4> Url: <%= app.url %> </h4>
        <div class='media-body'>
          <h5> Events: <br> </h5>
          <% app.events.each do |event| %>
          <p> <%= event.name %> </p>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/welcome/brandon.html.erb
<div class="skill-wrap clearfix">

    <div class="center wow fadeInDown">
      <h2>Who is Brandon?</h2>

        <p>I began my journey into programming as a vital creative endeavor,
           a way to work and create simultaneously.
        </p>

        <p>
           I come from a teaching background. My traditional degree is in English and Education and for the past four years I have been a middle school teacher, teaching 7-8th grade English and History.
           I have always had a drive to help people and to lead them to better and stronger senses of self. In code I seek to do the same.
        </p>

        <p>
           I was drawn to web development because I realized the power the breadth that the web had to offer. The growth of the web and the increased access to it appeal to my sense of broad outreach.
           I hope to be able to use the web to reach people in meaningful and compelling ways.
        </p>

     </div>

     <div class="center wow fadeInDown">
       <h2> Brandon's Portfolio </h2>
     </div>

    <div class="row clearfix">
      <div class="col-md-4 col-sm-6">
        <div class="single-profile-top wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
          <div class="media">
            <div class="media-body">
              <h2>Bloccit</h2>
              <h3>Reddit Clone</h3>
              <ul class="tag clearfix">
                <li> <a href="http://bwieber-bloccit.herokuapp.com/" class='btn btn-default btn-md'> <i class="fa fa-star"> </i> <span class="network-name">Website</span></a> </li>
                <li> <a href="https://github.com/BWieber/BasicRailsApp" class='btn btn-default btn-md'> <i class="fa fa-github"> </i> <span class="network-name">GitHub Repo</span></a> </li>
              </ul>

              <ul class="social_icons">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
              </ul>
            </div>
          </div><!--/.media -->
          <p>This project was my entry into Ruby and Ruby on Rails. It replicates many of reddit's UI, allowing a user to create topics, posts and comments. It also allows a user to favorite posts they like, and up/down vote any post.</p>
        </div>
      </div><!--/.col-lg-4 -->


      <div class="col-md-4 col-sm-6 col-md-offset-2">
        <div class="single-profile-top wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
          <div class="media">

            <div class="media-body">
              <h2>Blocitoff</h2>
              <h3> Self-Destructing ToDo List</h3>
              <ul class="tag clearfix">
                <li> <a href="http://bwieber-blocitoff.herokuapp.com/" class='btn btn-default btn-md'> <i class="fa fa-star"> </i> <span class="network-name">Website</span></a> </li>
                <li> <a href="https://github.com/BWieber/Blocitoff" class='btn btn-default btn-md'> <i class="fa fa-github"> </i> <span class="network-name">GitHub Repo</span></a> </li>
              </ul>
              <ul class="social_icons">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
              </ul>
            </div>
          </div><!--/.media -->
          <p> Blocitoff is a self-destructing task list that automatically deletes tasks if not completed within 7 days. Users create individual accounts by providing a username, email address, and password. They can then create tasks and delete them when finished.</p>
        </div>
      </div><!--/.col-lg-4 -->
    </div> <!--/.row -->
    <div class="row team-bar">
      <div class="first-one-arrow hidden-xs">
        <hr>
      </div>
      <div class="first-arrow hidden-xs">
        <hr> <i class="fa fa-angle-up"></i>
      </div>
      <div class="second-arrow hidden-xs">
        <hr> <i class="fa fa-angle-down"></i>
      </div>
      <div class="third-arrow hidden-xs">
        <hr> <i class="fa fa-angle-up"></i>
      </div>
      <div class="fourth-arrow hidden-xs">
        <hr> <i class="fa fa-angle-down"></i>
      </div>
    </div> <!--skill_border-->

    <div class="row clearfix">
      <div class="col-md-4 col-sm-6 col-md-offset-2">
        <div class="single-profile-bottom wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="600ms">
          <div class="media">


            <div class="media-body">
              <h2>Blocipedia</h2>
              <h3>Wiki Collaboration App</h3>
              <ul class="tag clearfix">
                <li> <a href="http://bwieber-blocipedia.herokuapp.com/" class='btn btn-default btn-md'> <i class="fa fa-star"> </i> <span class="network-name">Website</span></a> </li>
                <li> <a href="https://github.com/BWieber/Blocipedia" class='btn btn-default btn-md'> <i class="fa fa-github"> </i> <span class="network-name">GitHub Repo</span></a> </li>
              </ul>
              <ul class="social_icons">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
              </ul>
            </div>
          </div><!--/.media -->
          <p>A Wikipedia clone with a variety of user roles. Standard users can create and edit wikis, premium users can create private wikis with collaborators and admins can do it all.</p>
        </div>
      </div>
      <div class="col-md-4 col-sm-6 col-md-offset-2">
        <div class="single-profile-bottom wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="600ms">
          <div class="media">

            <div class="media-body">
              <h2>Blocmarks</h2>
              <h3>Bookmark Sharing Tool</h3>
              <ul class="tag clearfix">
                <li> <a href="http://bwieber-blocmarks.herokuapp.com/" class='btn btn-default btn-md'> <i class="fa fa-star"> </i> <span class="network-name">Website</span></a> </li>
                <li> <a href="https://github.com/BWieber/Blocmarks" class='btn btn-default btn-md'> <i class="fa fa-github"> </i> <span class="network-name">GitHub Repo</span></a> </li>
              </ul>
              <ul class="social_icons">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
              </ul>
            </div>
          </div><!--/.media -->
          <p> An application that allows a user to bookmark URLs via email, peruse other user's bookmarks and maintain a personal index of categorized bookmarks.</p>
        </div>
      </div>
    </div>	<!--/.row-->
  </div><!--section-->
</div><!--/.container-->
</section><!--/about-us-->

app/views/welcome/code.html.erb
<div class="skill-wrap clearfix">

    <div class="center wow fadeInDown">
      <h2>Inside Blocmetrics</h2>
      <p class="lead">The code necessary to start your own custom analytics. </p>
    </div>

  <div class="team">
    <div class="center wow fadeInDown">
      <h2>Javascript API Code</h2>
      <p class="lead">Javascript is at the heart of the analytics process. This code is located in the application.js file. <br> Ensure that your POST action is set to your website. <br> It's also vital to rails_ENV=production rake assets:precompile to get the JS to run in production.</p>
      <pre>
       var blocmetrics = {};
       blocmetrics.report = function(eventName) {
       event = {event: { name: eventName}};
       var request = new XMLHttpRequest();
       request.open("POST", "http:bwieber-blocmetrics.herokuapp.comapievents", true);
       request.setRequestHeader('Content-Type', 'applicationjson');
       request.send(JSON.stringify(event));
       }
      </pre>
    </div>
  </div>

  <div class="team">
    <div class="center wow fadeInDown">
      <h2> The content_for helper method</h2>
      <p class="lead"> From <strong>'Rails Guides'</strong>: The content_for method allows you to insert content into a named yield block in your layout. <br> It's also useful for inserting tags that load page-specific JavaScript or css files into the header of an otherwise generic layout."</p>
      <p> Within your layouts/application.html.erb, use the following code <i>before</i> your body and html close tags: </p>

      <code>  &lt<%= "%= yield " + ":analytic %" %>&gt </code>

      <p> This allows for you to call the content_for method on any view page, injecting the analytics JS onto that page. </p>
      <pre>
      &lt<%= "% content_for " + ":analytic %" %>&gt
      &lt<%= 'script type="text/javascript"> $(document).ready(function(){ blocmetrics.report("Visited_home_page"); }); </script' %>&gt
      &lt<%= "% end %" %>&gt
      </pre>

      <p> With this done, whatever message you put within the blocmetrics.report parameters will be sent in the form of JSON data to whatever site you have set to receive it. Happy Analyizing! </p>

    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<section id="feature" >
    <div class="container">
       <div class="center wow fadeInDown">
            <h2> BLOCMETRICS </h2>
            <p class="lead"> A personal API built to understand the interaction between apps. </p>
        </div>

        <div class="row">
            <div class="features">
                <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                    <div class="feature-wrap">
                        <i class="fa fa-bullhorn"></i>
                        <h2>Client-Side Javascript</h2>
                        <h3>An extended version of JavaScript that enables the enhancement and manipulation of web pages and client browsers</h3>
                    </div>
                </div>

                <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                    <div class="feature-wrap">
                        <i class="fa fa-comments"></i>
                        <h2>Chartkick</h2>
                        <h3>The Chartkick Gem allows for the use of beautiful and descriptive charts.</h3>
                    </div>
                </div>

                <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                    <div class="feature-wrap">
                        <i class="fa fa-cloud-download"></i>
                        <h2>JSON, CORS and CURL</h2>
                        <h3>These concepts form the foundation of my API.</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="recent-works">
    <div class="container">
        <div class="center wow fadeInDown">
            <h2>Project Graphs</h2>
            <p class="lead"> These graphs display data from my Rails apps made during my <a href='http://www.bloc.io'>Bloc</a> apprenticeship.</p>
        </div>

        <div class="row">
          <div class="col-sm-4">
              <div class="recent-work-wrap">
                <div class="recent-work-inner">
                  <h3> Bloccit </h3>
                  <p> Reddit Clone. Users can do CRUD actions on posts, up/down vote and favorite posts they like. </p>
                  <p> <%= pie_chart RegisteredApplication.find_by(name: 'Bloccit').events.group(:name).count %> </p>
                </div>
              </div>
            </div>


            <div class="col-sm-4">
              <div class="recent-work-wrap">
                <div class="recent-work-inner">
                  <h3> Blocitoff </h3>
                  <p>A ToDo List application utilizing rake automation.</p>
                  <p> <%= pie_chart RegisteredApplication.find_by(name: 'Blocitoff').events.group(:name).count %> </p>
                </div>
              </div>
            </div>

          </div>

        </div>
    </div>
</section>